name: megasprite_example
description: Example app demonstrating megasprite sprite atlas rendering
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^3.6.0
  desktop_drop: ^0.5.0
  flutter:
    sdk: flutter
  megasprite:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
